### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by fredericks** [italia/spid-cie-oidc-php#10]
Ciao,

forse mi è sfuggito qualcosa, ma non ho trovato documentazione a riguardo.

Quando eseguo composer install mi chiede diversi parametri e non sono sicuro come compilarli:

Nello specifico:

**authority_hint** con valore di default http://trust-anchor.org:8000/

Su questo non ho trovato informazioni neanche sulle linee guida. 

**redirect_uri** 

Ho lasciato quello proposto (in base al nome che ho dato all'enpoint del relying party):

 /spid_openid/test.php

Forse dipende dal fatto di non avere compilato bene i parametri ma, quando cerco di andare su **/spid_openid/oidc/rp/authz** come descritto sulla guida va a cercare un file sqlite che non c'è:

**../data/store-rp.sqlite**

Unable to open database: bad parameter or other API misuse [C:\Sviluppo\QUESTIT\spid-cie-oidc-php-main\lib\OIDC\RP\Database.php:45]

**Comment by fredericks** [comment]
Ok, ho risolto il problema del file sqlite.

Quando cerco di scelgo di accedere con lo spid usando l'unica opzione disponibile viene reindirizzato e dà giustamente un errore:

Unable to reach http://trust-anchor.org:8000/oidc/op/.well-known/openid-federation

Perché quell'indirizzo (http://trust-anchor.org:8000/) non esiste

![image](https://user-images.githubusercontent.com/7090975/175004677-0a429eae-9fc3-4ccd-98ed-ec91fac87f86.png)

Devo implementare l'endpoint in questione? Cos'è authority_hint?

**Comment by peppelinux** [comment]
nel readme di spid-cie-oidc-django alla voce docker vi è l'indicazione su come modificare il file hosts di sistema per ottenere queste risoluzioni

in alternativa abbiamo anche una soluzione più smart sotto forma di PR che spero di unire appena possibile

authority_hints lo trovi qui
https://openid.net/specs/openid-connect-federation-1_0.html#rfc.section.3.1

**Comment by peppelinux** [comment]
come hai risolto il problema del sqlite?

**Comment by fredericks** [comment]
> come hai risolto il problema del sqlite?

Ho visto che cercava di creare il file e creare le tabella, il costruttore di sqlite aveva anche il flag di creazione ma non riusciva comunque a creare il file. Ho creato manualmente la cartella data dove gli serviva ed a quel punto è riuscito a creare il file e riempirlo.

C'è qualcosa che mi sfugge su tutta la procedura. Con questo progetto cosa posso riuscire a fare? Creare un relying party ed usarlo per accedere con lo spid? Vale per tutti gli identity provider? Ho visto che sono tutti commentati nel codice (aruba, poste)

In ogni caso usando l'unico disponibile (spid) cerca poi di collegarsi all'indirizzo dell'authority_hint. E' obbligatorio implementarlo?

Non ho ben capito cosa devo implementare per riuscire a testarlo.

**Comment by damikael** [comment]
Buongiorno @fredericks ,
questo progetto permette di implementare un RP conforme alle Linee Guida OIDC SPID/CIE (https://www.agid.gov.it/sites/default/files/repository_files/linee_guida_openid_connect_in_spid.pdf) e ad OIDC Federation (https://openid.net/specs/openid-connect-federation-1_0.html) per la risoluzione dei metadata degli OP.
Gli IdP SPID e CIE sono attualmente in fase di avvio delle piattaforme OIDC, pertanto ancora non è possibile integrare i propri RP verso gli OP SPID e CIE reali in OIDC (ancora per poco). 
Per effettuare dei test di integrazione, pertanto, occorre interfacciare il proprio RP (implementato tramite spid-cie-oidc-php) ad un OP di test e ad una federazione di test. Il riferimento di authority_hint è esattamente il riferimento al Trust Anchor della federazione di test che occorre configurare per risolvere i metadata secondo le specifiche di OIDC Federation.
Puoi utilizzare come OP di test e federazione di test i relativi progetti che trovi al repo https://github.com/italia/spid-cie-oidc-django.

In particolare:
- documentazione per il setup di OP di test e federazione di test
https://github.com/italia/spid-cie-oidc-django#setup
- documentazione per il setup di spid-cie-oidc-php come RP basic
https://github.com/italia/spid-cie-oidc-php#setup
- documentazione per avviare un progetto completo per WordPress basato su spid-cie-oidc-php completo di OP e federazione di test
https://github.com/italia/spid-cie-oidc-php/blob/main/doc/example-wordpress/README.md
- documentazione per avviare un progetto completo per Drupal basato su spid-cie-oidc-php completo di OP e federazione di test
https://github.com/italia/spid-cie-oidc-php/blob/main/doc/example-drupal/README.md

**Comment by damikael** [comment]
I file di spid-cie-oidc-php devono essere rilasciati in una directory esterna alla root del web server.
Quindi dalla directory di spid-cie-oidc-php occorre lanciare il comando di setup:
`composer install`
Il comando permette di eseguire l'installazione in maniera interattiva e crea nella root del webserver, nella directory indicata durante l'installazione, tutto il necessario.
I file del repo spid-cie-oidc-php NON devono essere rilasciati in una directory pubblicamente accessibile da web in quanto contengono configurazioni e certificati che devono essere mantenuti riservati.

**Comment by fredericks** [comment]
Ho riprovato il composer install lasciando quasi tutto di default. Questi i parametri salienti:

            "client_id": "http://relying-party-php.org:8003",

Il RP dovrebbe essere creato dal composer install?
A cosa deve puntare relying-party-php.org:8003?

            "authority_hint": "http:\/\/trust-anchor.org:8000\/",

Qui devo scaricare il progetto 
https://github.com/italia/spid-cie-oidc-django

            "redirect_uri": "\/spid_openid\/test.php"

E questo credo vada bene, corretto?

**Comment by damikael** [comment]
è possibile seguire come riferimento la documentazione per WordPress:
https://github.com/italia/spid-cie-oidc-php/blob/main/doc/example-wordpress/README.md

**Comment by Zhigalin** [comment]
@damikael un info cortesemente, questa libreria puo essere collegata all'authority di mininterno quindi usata in produzione?
Vedo anche che nel master l'ultimo commit risale a maggio dell'anno scorso, e' da usare il ramo dev?

Adesso ci stanno spingendo fortemente per abbandonare SAML ma le info su come fare con OIDC sono abbastanza scarse...

**Comment by damikael** [comment]
Conviene utilizzare il ramo dev, ancora non è completamente stabile ma posso confermare che funziona con l'ambiente di produzione CIE.
