### ISSUE TITLE
Implementation on Wordpress

### ISSUE THREAD

**Issue by gfsoluzioni** [italia/spid-cie-oidc-php#11]
Hi , would there be a guide to implement this module on a site made in Wordpress?

**Comment by damikael** [comment]
Hi, you can setup the proxy and configure on WordPress a plugin for OIDC as:
https://wordpress.org/plugins/daggerhart-openid-connect-generic/

See also:
https://github.com/italia/spid-cie-oidc-php/blob/main/doc/example-wordpress/README.md
