### ISSUE TITLE
Usage as a generic library

### ISSUE THREAD

**Issue by cicnavi** [italia/spid-cie-oidc-php#12]
Hi,

thank you for making this repo available for the community. I have a question about the possibility of using this package for generic OIDC Federation Relying Party (not for SPID or CIE), since usage as a library is (somewhat) indicated in the readme.

So, my intention is to use spid-cie-oidc-php federation related classes for entity statement, trust chain resolution, etc. in another OIDC RP package.

I have gone ahead and tried to instalall spid-cie-oidc-php as a dependency using composer

`composer require linfaservice/spid-cie-oidc-php`

I got a warning about missing / not known 'spid-sp-access-button' dependency. Then I added the following repo indication in my composer.json

```
"repositories": {
    "spid-sp-access-button": {
      "type": "package",
      "package": {
        "name": "italia/spid-sp-access-button",
        "version": "1.0.0",
        "source": {
          "url": "https://github.com/italia/spid-sp-access-button",
          "type": "git",
          "reference": "master"
        }
      }
    }
  },
```

After that, the composer installation was successful. 

Next, my intention was to try to use EntityStatement class. The thing I encountered is this: I see in sample RP configs there is 'redirect_uri' property available, however I see that the redirect URI is hardcoded in method EntityStatement ::makeFromConfig() , and will not be correct for my RP, line https://github.com/italia/spid-cie-oidc-php/blob/299bbbf012ff766d77b2529f3c1f8f3d94aca436/lib/Federation/EntityStatement.php#L92

Also, another example of hardcoded redirect_uri (not from config) is in AuthenticationRequest class, line https://github.com/italia/spid-cie-oidc-php/blob/299bbbf012ff766d77b2529f3c1f8f3d94aca436/lib/OIDC/RP/AuthenticationRequest.php#L71

In AuthenticationRequest class I also see SPID / CIE related configs and parameters set...

I guess this all was made on purpose, and since you have the whole TA/OP/RP containerized test environment available...

The question I'm trying to ask, is usage as a generic class library plausible at all or is this package intended as is, for SPID CIE? Is creating generic class library something that you would consider at all?

Some background: as part of GEANT Trust & Incubator activity we are searching for existing PHP OIDC Fed capable RPs, and came across this repo. We are planning on implementing OIDC Fed capable RP in SimpleSAMLphp: https://wiki.geant.org/display/GWP5/OIDCfed+support+on+SimpleSAMLphp

**Comment by damikael** [comment]
Hi @cicnavi,

sorry for late reply. I'm pleased for your interest into spid-cie-oidc-php.
The purpose of project is mainly focused on SPID/CIE but it can be extended to be used as a generic class library.
Even if this task is not planned for now, every contributions is always well accepted.
If you want to collaborate on the project to let it capable to be used as an external library on other projects, as SimpleSAMLphp, you can open PR and assign it to me for review.
It will be great to work together.


Michele D'Amico (@damikael)

**Comment by damikael** [comment]
#17 merged.
TYVM
