### ISSUE TITLE
Errore "Failed to establish the Trust" all'invio della richiesta al sistema di federazione di test

### ISSUE THREAD

**Issue by evelina-a** [italia/spid-cie-oidc-php#15]
Salve, 
ho fatto il setup del progetto https://github.com/italia/spid-cie-oidc-django#setup e funziona tutto correttamente, riesco a fare un login con SPID. 

Invece se mando la richiesta da questo progetto ottengo questo errore

<img width="759" alt="Schermata 2023-06-23 alle 08 55 55" src="https://github.com/italia/spid-cie-oidc-php/assets/8981437/645f600e-89d2-4f7d-8718-0b8cb4a10ed8">

La riposta dalla federazione di test è:

` /oidc/rp/redirect?error=invalid_request&error_description=Failed+to+establish+the+Trust&state=MTUgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA`

Sto eseguendo tutto in locale su localhost:9999 e ho configurato questo indirizzo come client_id

Nel log non vedo niente. 

A cosa potrebbe essere dovuto l'errore? 

E' possibile utilizzare anche il validator SPID per verificare il sistema?

**Comment by damikael** [comment]
Buongiorno @evelina-a ,
assicurati di aver registrato correttamente il RP sul pannello di amministrazione del TA esposto da spid-cie-oidc-django.
Trovi qui alcune indicazioni di esempio: 
https://github.com/italia/spid-cie-oidc-php/blob/main/doc/example-wordpress/README.md#how-to-run-with-docker

Il [Validator SPID OIDC RP](https://github.com/AgID/spid-oidc-check-rp) può essere utilizzato per verificare il metadata (.well-known/openid-federation) e il flusso OIDC Core, mentre non può essere utilizzato per la verifica della risoluzione della trust chain secondo OpenID Federation.

Michele D'Amico (@damikael)

**Comment by evelina-a** [comment]
Grazie, mi ero persa i passaggi di registrazione. Adesso funziona e riesco a fare il login correttamente.
